myData = [
[1,"Monument","https://en.wikipedia.org/wiki/Monument"],
[2,"Scheduled monument","https://en.wikipedia.org/wiki/Scheduled_monument"],
[3,"The Monuments Men","https://en.wikipedia.org/wiki/The_Monuments_Men"],
[4,"Group of Monuments at Mahabalipuram","https://en.wikipedia.org/wiki/Group_of_Monuments_at_Mahabalipuram"],
[5,"List of tallest statues","https://en.wikipedia.org/wiki/List_of_tallest_statues"],
[6,"Hampi","https://en.wikipedia.org/wiki/Hampi"],
[7,"List of areas in the United States National Park System","https://en.wikipedia.org/wiki/List_of_areas_in_the_United_States_National_Park_System"],
[8,"Monuments to an Elegy","https://en.wikipedia.org/wiki/Monuments_to_an_Elegy"],
[9,"List of Confederate monuments and memorials","https://en.wikipedia.org/wiki/List_of_Confederate_monuments_and_memorials"],
[10,"List of national monuments of the United States","https://en.wikipedia.org/wiki/List_of_national_monuments_of_the_United_States"],
[11,"Stonehenge","https://en.wikipedia.org/wiki/Stonehenge"],
[12,"Monument Valley","https://en.wikipedia.org/wiki/Monument_Valley"],
[13,"Natural monument","https://en.wikipedia.org/wiki/Natural_monument"],
[14,"Qutb Minar complex","https://en.wikipedia.org/wiki/Qutb_Minar_complex"],
[15,"Khajuraho Group of Monuments","https://en.wikipedia.org/wiki/Khajuraho_Group_of_Monuments"],
[16,"Yonaguni Monument","https://en.wikipedia.org/wiki/Yonaguni_Monument"],
[17,"List of monuments of Italy","https://en.wikipedia.org/wiki/List_of_monuments_of_Italy"],
[18,"Foxe's Book of Martyrs","https://en.wikipedia.org/wiki/Foxe%27s_Book_of_Martyrs"],
[19,"Nico Ditch","https://en.wikipedia.org/wiki/Nico_Ditch"],
[20,"List of Lebanese monuments","https://en.wikipedia.org/wiki/List_of_Lebanese_monuments"],
[21,"Medieval art","https://en.wikipedia.org/wiki/Medieval_art"],
[22,"Stonehenge, Avebury and Associated Sites","https://en.wikipedia.org/wiki/Stonehenge,_Avebury_and_Associated_Sites"],
[23,"List of monument and memorial controversies in the United States","https://en.wikipedia.org/wiki/List_of_monument_and_memorial_controversies_in_the_United_States"],
[24,"Amit Nimade","https://en.wikipedia.org/wiki/Amit_Nimade"],
[25,"Monuments (metal band)","https://en.wikipedia.org/wiki/Monuments_(metal_band)"],
[26,"Ten Commandments","https://en.wikipedia.org/wiki/Ten_Commandments"],
[27,"Washington Monument","https://en.wikipedia.org/wiki/Washington_Monument"],
[28,"Pattadakal","https://en.wikipedia.org/wiki/Pattadakal"],
[29,"Mtskheta","https://en.wikipedia.org/wiki/Mtskheta"],
[30,"Robert Edward Lee (sculpture)","https://en.wikipedia.org/wiki/Robert_Edward_Lee_(sculpture)"],
[31,"The monument","https://en.wikipedia.org/wiki/The_monument"],
[32,"Megalith","https://en.wikipedia.org/wiki/Megalith"],
[33,"Archaeological Survey of India","https://en.wikipedia.org/wiki/Archaeological_Survey_of_India"],
[34,"List of World Heritage sites in India","https://en.wikipedia.org/wiki/List_of_World_Heritage_sites_in_India"],
[35,"Cadaver tomb","https://en.wikipedia.org/wiki/Cadaver_tomb"],
[36,"Removal of Confederate monuments and memorials","https://en.wikipedia.org/wiki/Removal_of_Confederate_monuments_and_memorials"],
[37,"Lists of Indian Monuments of National Importance","https://en.wikipedia.org/wiki/Lists_of_Indian_Monuments_of_National_Importance"],
[38,"Ellis Island","https://en.wikipedia.org/wiki/Ellis_Island"],
[39,"National monuments of Spain","https://en.wikipedia.org/wiki/National_monuments_of_Spain"],
[40,"St. Mary's Islands","https://en.wikipedia.org/wiki/St._Mary%27s_Islands"],
[41,"The Motherland Calls","https://en.wikipedia.org/wiki/The_Motherland_Calls"],
[42,"Monument historique","https://en.wikipedia.org/wiki/Monument_historique"],
[43,"Marymount High School","https://en.wikipedia.org/wiki/Marymount_High_School"],
[44,"List of scheduled monuments","https://en.wikipedia.org/wiki/List_of_scheduled_monuments"],
[45,"Statue of Lenin, Seattle","https://en.wikipedia.org/wiki/Statue_of_Lenin,_Seattle"],
[46,"Devils Tower","https://en.wikipedia.org/wiki/Devils_Tower"],
[47,"Skanderbeg Monument","https://en.wikipedia.org/wiki/Skanderbeg_Monument"],
[48,"Hearst Castle","https://en.wikipedia.org/wiki/Hearst_Castle"],
[49,"Sanchi","https://en.wikipedia.org/wiki/Sanchi"],
[50,"List of megalithic monuments in Ireland","https://en.wikipedia.org/wiki/List_of_megalithic_monuments_in_Ireland"],
[51,"Tomb","https://en.wikipedia.org/wiki/Tomb"],
[52,"Qutb Minar","https://en.wikipedia.org/wiki/Qutb_Minar"],
[53,"Hawa Mahal","https://en.wikipedia.org/wiki/Hawa_Mahal"],
[54,"Lodi Gardens","https://en.wikipedia.org/wiki/Lodi_Gardens"],
[55,"Arc de Triomphe","https://en.wikipedia.org/wiki/Arc_de_Triomphe"],
[56,"Ancient monument","https://en.wikipedia.org/wiki/Ancient_monument"],
[57,"Historic Monuments of Ancient Kyoto (Kyoto, Uji and Otsu Cities)","https://en.wikipedia.org/wiki/Historic_Monuments_of_Ancient_Kyoto_(Kyoto,_Uji_and_Otsu_Cities)"],
[58,"Aihole","https://en.wikipedia.org/wiki/Aihole"],
[59,"Cultural heritage","https://en.wikipedia.org/wiki/Cultural_heritage"],
[60,"International Day For Monuments and Sites","https://en.wikipedia.org/wiki/International_Day_For_Monuments_and_Sites"],
[61,"AMASR Act","https://en.wikipedia.org/wiki/AMASR_Act"],
[62,"Spire of Dublin","https://en.wikipedia.org/wiki/Spire_of_Dublin"],
[63,"Phronesis (Monuments album)","https://en.wikipedia.org/wiki/Phronesis_(Monuments_album)"],
[64,"Charminar","https://en.wikipedia.org/wiki/Charminar"],
[65,"Hollywood Walk of Fame","https://en.wikipedia.org/wiki/Hollywood_Walk_of_Fame"],
[66,"Wiki Loves Monuments","https://en.wikipedia.org/wiki/Wiki_Loves_Monuments"],
[67,"Seven Wonders of the Ancient World","https://en.wikipedia.org/wiki/Seven_Wonders_of_the_Ancient_World"],
[68,"Nagasaki Peace Park","https://en.wikipedia.org/wiki/Nagasaki_Peace_Park"],
[69,"American Battle Monuments Commission","https://en.wikipedia.org/wiki/American_Battle_Monuments_Commission"],
[70,"Mughal architecture","https://en.wikipedia.org/wiki/Mughal_architecture"],
[71,"Buzludzha monument","https://en.wikipedia.org/wiki/Buzludzha_monument"],
[72,"New7Wonders of the World","https://en.wikipedia.org/wiki/New7Wonders_of_the_World"],
[73,"Frogmore","https://en.wikipedia.org/wiki/Frogmore"],
[74,"Kiyomizu-dera","https://en.wikipedia.org/wiki/Kiyomizu-dera"],
[75,"Tourism in Japan","https://en.wikipedia.org/wiki/Tourism_in_Japan"],
[76,"Olmec colossal heads","https://en.wikipedia.org/wiki/Olmec_colossal_heads"],
[77,"12 Treasures of Spain","https://en.wikipedia.org/wiki/12_Treasures_of_Spain"],
[78,"Monuments and Forts of the Deccan Sultanate","https://en.wikipedia.org/wiki/Monuments_and_Forts_of_the_Deccan_Sultanate"],
[79,"Cadastral surveying","https://en.wikipedia.org/wiki/Cadastral_surveying"],
[80,"Minerva","https://en.wikipedia.org/wiki/Minerva"],
[81,"National Monuments Record","https://en.wikipedia.org/wiki/National_Monuments_Record"],
[82,"List of ancient monuments in Rome","https://en.wikipedia.org/wiki/List_of_ancient_monuments_in_Rome"],
[83,"Art and architecture of the Pallavas","https://en.wikipedia.org/wiki/Art_and_architecture_of_the_Pallavas"],
[84,"Aam Khas Bagh","https://en.wikipedia.org/wiki/Aam_Khas_Bagh"],
[85,"Frédéric Auguste Bartholdi","https://en.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Auguste_Bartholdi"],
[86,"Victoria Memorial, Kolkata","https://en.wikipedia.org/wiki/Victoria_Memorial,_Kolkata"],
[87,"Robert Gould Shaw Memorial","https://en.wikipedia.org/wiki/Robert_Gould_Shaw_Memorial"],
[88,"Henge","https://en.wikipedia.org/wiki/Henge"],
[89,"The Motherland Monument","https://en.wikipedia.org/wiki/The_Motherland_Monument"],
[90,"Cinque Terre","https://en.wikipedia.org/wiki/Cinque_Terre"],
[91,"Skara Brae","https://en.wikipedia.org/wiki/Skara_Brae"],
[92,"List of statues of Vladimir Lenin","https://en.wikipedia.org/wiki/List_of_statues_of_Vladimir_Lenin"],
[93,"Stari Most","https://en.wikipedia.org/wiki/Stari_Most"],
[94,"Victory Arch","https://en.wikipedia.org/wiki/Victory_Arch"],
[95,"Harry L. Ettlinger","https://en.wikipedia.org/wiki/Harry_L._Ettlinger"],
[96,"Tourism in Karnataka","https://en.wikipedia.org/wiki/Tourism_in_Karnataka"],
[97,"Grave","https://en.wikipedia.org/wiki/Grave"],
[98,"Ryan Zinke","https://en.wikipedia.org/wiki/Ryan_Zinke"],
[99,"George L. Stout","https://en.wikipedia.org/wiki/George_L._Stout"],
[100,"Ronald Edmond Balfour","https://en.wikipedia.org/wiki/Ronald_Edmond_Balfour"],
];

function link() {
myData.forEach(myFunc);
}

function myFunc(value) {
document.write("<tr><td>"+value[0]+"</td><td>"+value[1]+"</td><td><a href='"+value[2]+"'>"+value[2]+"</a></td></tr>");
}
