myData = [
[1,"CJ","https://en.wikipedia.org/wiki/CJ"],
[2,"Jeep CJ","https://en.wikipedia.org/wiki/Jeep_CJ"],
[3,"CJ Group","https://en.wikipedia.org/wiki/CJ_Group"],
[4,"CJ ENM","https://en.wikipedia.org/wiki/CJ_ENM"],
[5,"CJ Entertainment","https://en.wikipedia.org/wiki/CJ_Entertainment"],
[6,"CJ E&M","https://en.wikipedia.org/wiki/CJ_E%26M"],
[7,"CJ Jones","https://en.wikipedia.org/wiki/CJ_Jones"],
[8,"CJ Adams","https://en.wikipedia.org/wiki/CJ_Adams"],
[9,"CJ Foodville","https://en.wikipedia.org/wiki/CJ_Foodville"],
[10,"Shop CJ","https://en.wikipedia.org/wiki/Shop_CJ"],
[11,"CJ Mac","https://en.wikipedia.org/wiki/CJ_Mac"],
[12,"CJ McCollum","https://en.wikipedia.org/wiki/CJ_McCollum"],
[13,"CJ Cup","https://en.wikipedia.org/wiki/CJ_Cup"],
[14,"CJ7","https://en.wikipedia.org/wiki/CJ7"],
[15,"CJ CGV","https://en.wikipedia.org/wiki/CJ_CGV"],
[16,"CJ Fly","https://en.wikipedia.org/wiki/CJ_Fly"],
[17,"CJ Verdell","https://en.wikipedia.org/wiki/CJ_Verdell"],
[18,"CJ Hendry","https://en.wikipedia.org/wiki/CJ_Hendry"],
[19,"C. J. de Mooi","https://en.wikipedia.org/wiki/C._J._de_Mooi"],
[20,"Papa CJ","https://en.wikipedia.org/wiki/Papa_CJ"],
[21,"Nanchang CJ-6","https://en.wikipedia.org/wiki/Nanchang_CJ-6"],
[22,"ACAE CJ-1000A","https://en.wikipedia.org/wiki/ACAE_CJ-1000A"],
[23,"CJ CheilJedang","https://en.wikipedia.org/wiki/CJ_CheilJedang"],
[24,"Cessna CitationJet/M2","https://en.wikipedia.org/wiki/Cessna_CitationJet/M2"],
[25,"CJ Gibson","https://en.wikipedia.org/wiki/CJ_Gibson"],
[26,"CJ-10 (missile)","https://en.wikipedia.org/wiki/CJ-10_(missile)"],
[27,"CJ Ramos","https://en.wikipedia.org/wiki/CJ_Ramos"],
[28,"CJ Affiliate","https://en.wikipedia.org/wiki/CJ_Affiliate"],
[29,"CJ Hopkins","https://en.wikipedia.org/wiki/CJ_Hopkins"],
[30,"Madam C. J. Walker","https://en.wikipedia.org/wiki/Madam_C._J._Walker"],
[31,"Stone Music Entertainment","https://en.wikipedia.org/wiki/Stone_Music_Entertainment"],
[32,"CJ O Shopping","https://en.wikipedia.org/wiki/CJ_O_Shopping"],
[33,"Lana (wrestler)","https://en.wikipedia.org/wiki/Lana_(wrestler)"],
[34,"CJ Huyer","https://en.wikipedia.org/wiki/CJ_Huyer"],
[35,"Carl Johnson (Grand Theft Auto)","https://en.wikipedia.org/wiki/Carl_Johnson_(Grand_Theft_Auto)"],
[36,"CJ Fish","https://en.wikipedia.org/wiki/CJ_Fish"],
[37,"C. J. Anderson","https://en.wikipedia.org/wiki/C._J._Anderson"],
[38,"CJ the DJ","https://en.wikipedia.org/wiki/CJ_the_DJ"],
[39,"Jeep","https://en.wikipedia.org/wiki/Jeep"],
[40,"CJ Hamilton (footballer)","https://en.wikipedia.org/wiki/CJ_Hamilton_(footballer)"],
[41,"CJ-5","https://en.wikipedia.org/wiki/CJ-5"],
[42,"C. J. Ramone","https://en.wikipedia.org/wiki/C._J._Ramone"],
[43,"CJ Perez","https://en.wikipedia.org/wiki/CJ_Perez"],
[44,"Grand Theft Auto: San Andreas","https://en.wikipedia.org/wiki/Grand_Theft_Auto:_San_Andreas"],
[45,"CJ Stone","https://en.wikipedia.org/wiki/CJ_Stone"],
[46,"CJ KIFT","https://en.wikipedia.org/wiki/CJ_KIFT"],
[47,"Airbus A319","https://en.wikipedia.org/wiki/Airbus_A319"],
[48,"CJ Pony Parts","https://en.wikipedia.org/wiki/CJ_Pony_Parts"],
[49,"Carl Edwards Jr.","https://en.wikipedia.org/wiki/Carl_Edwards_Jr."],
[50,"CJ4","https://en.wikipedia.org/wiki/CJ4"],
[51,"Mnet (TV channel)","https://en.wikipedia.org/wiki/Mnet_(TV_channel)"],
[52,"CJ Navato","https://en.wikipedia.org/wiki/CJ_Navato"],
[53,"CJ Daugherty","https://en.wikipedia.org/wiki/CJ_Daugherty"],
[54,"CJ-6","https://en.wikipedia.org/wiki/CJ-6"],
[55,"4DX","https://en.wikipedia.org/wiki/4DX"],
[56,"Willys Hurricane engine","https://en.wikipedia.org/wiki/Willys_Hurricane_engine"],
[57,"C. J. Cron","https://en.wikipedia.org/wiki/C._J._Cron"],
[58,"Juice Robinson","https://en.wikipedia.org/wiki/Juice_Robinson"],
[59,"Warren E. Burger","https://en.wikipedia.org/wiki/Warren_E._Burger"],
[60,"Jeep Wrangler (YJ)","https://en.wikipedia.org/wiki/Jeep_Wrangler_(YJ)"],
[61,"Jeep Wrangler","https://en.wikipedia.org/wiki/Jeep_Wrangler"],
[62,"John Marshall","https://en.wikipedia.org/wiki/John_Marshall"],
[63,"C. J. Pearson","https://en.wikipedia.org/wiki/C._J._Pearson"],
[64,"General Electric CJ805","https://en.wikipedia.org/wiki/General_Electric_CJ805"],
[65,"CJ Tañedo","https://en.wikipedia.org/wiki/CJ_Ta%C3%B1edo"],
[66,"General Electric CJ610","https://en.wikipedia.org/wiki/General_Electric_CJ610"],
[67,"CJ Baran","https://en.wikipedia.org/wiki/CJ_Baran"],
[68,"CJ Camerieri","https://en.wikipedia.org/wiki/CJ_Camerieri"],
[69,"Honda CJ series","https://en.wikipedia.org/wiki/Honda_CJ_series"],
[70,"William Rehnquist","https://en.wikipedia.org/wiki/William_Rehnquist"],
[71,"Thy Art Is Murder","https://en.wikipedia.org/wiki/Thy_Art_Is_Murder"],
[72,"C. J. Sansom","https://en.wikipedia.org/wiki/C._J._Sansom"],
[73,"C. J. Wilson","https://en.wikipedia.org/wiki/C._J._Wilson"],
[74,"A Dog's Journey","https://en.wikipedia.org/wiki/A_Dog%27s_Journey"],
[75,"TVN (South Korean TV channel)","https://en.wikipedia.org/wiki/TVN_(South_Korean_TV_channel)"],
[76,"Flower Band","https://en.wikipedia.org/wiki/Flower_Band"],
[77,"CJ3","https://en.wikipedia.org/wiki/CJ3"],
[78,"CJ Wallis","https://en.wikipedia.org/wiki/CJ_Wallis"],
[79,"C. J. Mosley (linebacker)","https://en.wikipedia.org/wiki/C._J._Mosley_(linebacker)"],
[80,"List of Jeep vehicles","https://en.wikipedia.org/wiki/List_of_Jeep_vehicles"],
[81,"C. J. Cregg","https://en.wikipedia.org/wiki/C._J._Cregg"],
[82,"C. J. Vanston","https://en.wikipedia.org/wiki/C._J._Vanston"],
[83,"C. J. Mosley (defensive lineman)","https://en.wikipedia.org/wiki/C._J._Mosley_(defensive_lineman)"],
[84,"100 Things to Do Before High School","https://en.wikipedia.org/wiki/100_Things_to_Do_Before_High_School"],
[85,"C. J. Hunter","https://en.wikipedia.org/wiki/C._J._Hunter"],
[86,"CJ Skead","https://en.wikipedia.org/wiki/CJ_Skead"],
[87,"CJ Kettler","https://en.wikipedia.org/wiki/CJ_Kettler"],
[88,"CJ-1","https://en.wikipedia.org/wiki/CJ-1"],
[89,"Shraddha Musale","https://en.wikipedia.org/wiki/Shraddha_Musale"],
[90,"C. J. (given name)","https://en.wikipedia.org/wiki/C._J._(given_name)"],
[91,"The Bold and the Beautiful","https://en.wikipedia.org/wiki/The_Bold_and_the_Beautiful"],
[92,"A Dog's Journey (film)","https://en.wikipedia.org/wiki/A_Dog%27s_Journey_(film)"],
[93,"Willys MB","https://en.wikipedia.org/wiki/Willys_MB"],
[94,"CJ Stander","https://en.wikipedia.org/wiki/CJ_Stander"],
[95,"CJ Crew","https://en.wikipedia.org/wiki/CJ_Crew"],
[96,"Inter-Services Public Relations","https://en.wikipedia.org/wiki/Inter-Services_Public_Relations"],
[97,"I-Land","https://en.wikipedia.org/wiki/I-Land"],
[98,"CJ Follini","https://en.wikipedia.org/wiki/CJ_Follini"],
[99,"Christopher & Banks","https://en.wikipedia.org/wiki/Christopher_%26_Banks"],
[100,"Hongdu Yakovlev CJ-7","https://en.wikipedia.org/wiki/Hongdu_Yakovlev_CJ-7"],
];

function link() {
myData.forEach(myFunc);
}

function myFunc(value) {
document.write("<tr><td>"+value[0]+"</td><td>"+value[1]+"</td><td><a href='"+value[2]+"'>"+value[2]+"</a></td></tr>");
}
