gword = [{text: 'CJ', size: 46},
{text: 'Jeep CJ', size: 42},
{text: 'CJ Group', size: 38},
{text: 'CJ ENM', size: 30},
{text: 'CJ Entertainment', size: 22},
{text: 'CJ Jones', size: 18},
{text: 'CJ Adams', size: 14},
{text: 'CJ Foodville', size: 30},
{text: 'Shop CJ', size: 34},
{text: 'CJ Mac', size: 46},
{text: 'CJ McCollum', size: 30},
{text: 'CJ Cup', size: 26},
{text: 'CJ CGV', size: 10},
{text: 'CJ Fly', size: 18},
{text: 'CJ Verdell', size: 10},
{text: 'CJ Hendry', size: 22},
{text: 'Papa CJ', size: 30},
{text: 'CJ CheilJedang', size: 10},
{text: 'CJ Gibson', size: 26},
{text: 'CJ Ramos', size: 18},
{text: 'CJ Affiliate', size: 46},
{text: 'CJ Hopkins', size: 46},
{text: 'Stone Music Entertainment', size: 34},
{text: 'CJ O Shopping', size: 14},
{text: 'CJ Huyer', size: 10},
{text: 'CJ Fish', size: 42},
{text: 'CJ the DJ', size: 42},
{text: 'Jeep', size: 14},
{text: 'CJ Perez', size: 34},
{text: 'CJ Stone', size: 42},
{text: 'CJ KIFT', size: 22},
{text: 'CJ Pony Parts', size: 18},
{text: 'CJ Navato', size: 26},
{text: 'CJ Daugherty', size: 30},
{text: 'Willys Hurricane engine', size: 22},
{text: 'Juice Robinson', size: 30},
{text: 'Jeep Wrangler', size: 22},
{text: 'John Marshall', size: 34},
{text: 'CJ Tañedo', size: 14},
{text: 'CJ Baran', size: 34},
{text: 'CJ Camerieri', size: 22},
{text: 'Honda CJ series', size: 30},
{text: 'William Rehnquist', size: 42},
{text: 'Thy Art Is Murder', size: 34},
{text: 'Flower Band', size: 22},
{text: 'CJ Wallis', size: 18},
{text: 'List of Jeep vehicles', size: 38},
{text: 'CJ Skead', size: 42},
{text: 'CJ Kettler', size: 46},
{text: 'Shraddha Musale', size: 22},
{text: 'The Bold and the Beautiful', size: 22},
{text: 'Willys MB', size: 18},
{text: 'CJ Stander', size: 26},
{text: 'CJ Crew', size: 14},
{text: 'CJ Follini', size: 42}
];
